In [16]:
import pandas as pd

# getting the data
import pandas as pd
df = pd.read_csv('data/verses.csv')
data = df['Translation'].to_list()

In [33]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# instantiating the model
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
# applying in on data
tfidf_vectors = tfidf_vectorizer.fit_transform(data)

# feature_names
feature_names = tfidf_vectorizer.get_feature_names()

# putting it all together in a dataframe
document_term_matrix = pd.DataFrame(tfidf_vectors.T.todense(), index = feature_names)

,0,1,2,3,4,5,6,7,8,9,...,647,648,649,650,651,652,653,654,655,656
boyhood,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
to,0.072659,0.063644,0.0,0.075335,0.0,0.0,0.075423,0.0,0.064798,0.0,...,0.084295,0.0,0.081644,0.0,0.123987,0.0,0.076124,0.0,0.0,0.0
youth,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0

In [60]:
df = pd.read_csv('data/queries.csv')
queries = df['Verse'].to_list()
queries = [query.lower().translate(str.maketrans('','',string.punctuation)) for query in queries]
queries

[' where does the embodied soul passes at death',
 ' what are the appearance and disappearance of happiness and distress like',
 ' is there birth or death for the soul',
 ' does the soul ever cease to exist',
 ' can the soul be cut into pieces',
 ' can the soul be burned',
 ' can the soul be moistened',
 ' can the soul be withered',
 ' what does the vedas mainly deal with',
 ' who needs to rise above the modes of material nature',
 ' to whom can the purposes of vedas be served',
 ' how does lust develops and from that anger arises',
 ' how does one falls down into the material pool',
 ' how can one become free from all attachment and aversion',
 ' what is the time of awakening for the selfcontrolled',
 ' when is the night for the introspective sage',
 ' can the soul be destroyed by any means',
 ' how does anger arises',
 ' how does lust develops']

In [51]:
# let's test this for a sample query
query = 'boyhood to youth'

# getting the common words between query and our features
common = set(query.split()).intersection(set(feature_names))
ind = document_term_matrix.loc[common].apply(sum).sort_values(ascending = False).head(3).index.to_list()

for i in ind:
    print(data[i] + '\n')

As the embodied soul continuously passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death. A sober person is not bewildered by such a change.

To those who are constantly devoted to serving Me with love, I give the understanding by which they can come to Me.

Arjuna said: The sun-god Vivasvan is senior by birth to You. How am I to understand that in the beginning You instructed this science to him?